In [79]:
# 1. 길이가 10인 0-벡터를 만드세요.
import numpy as np

vArray = np.zeros((10), dtype = np.int32)
print(vArray)

[0 0 0 0 0 0 0 0 0 0]


In [91]:
# 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

vArray = np.arange(10)
x = np.where(vArray == 5-1, 1, 0)
print(x)

[0 0 0 0 1 0 0 0 0 0]


In [15]:
# 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.
vArray = np.arange(10 , 50)
print(vArray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
# 4. 위(3번) 벡터의 순서를 바꾸세요.
vArray = np.arange(10 , 50).tolist()
vArray.sort(reverse = True)

print(vArray)

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


In [19]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
# 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.
vArray = np.array([1,2,0,0,4,0])
x = vArray[vArray > 0]

print(x)

[1 2 4]


In [28]:
# 7. 3x3 단위 행렬(identity matrix)을 만드세요
x = np.identity(n=3, dtype = np.int8)
print (x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [37]:
# 8. 난수 원소를 가지는 3x3 행렬을 만드세요
np.random.seed(1000)

x = np.random.uniform(0,1,9).reshape(3,3)
print(x)

[[0.65358959 0.11500694 0.95028286]
 [0.4821914  0.87247454 0.21233268]
 [0.04070962 0.39719446 0.2331322 ]]


In [90]:
# 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.
aMin = np.argmin(x)
aMax = np.argmax(x)

#배열 형태로 가공하는 방법
# i = int(aMin / 3)
# j = int(aMin % 3)
# print('최소값 원소 : %f'% x[i][j])
#---------------------------------


#flatten사용
listx = x.flatten()

print('최소값 : '+ (str(listx[aMin])))
print('최대값 : '+ (str(listx[aMax])))

# i = int(aMax / 3)
# j = int(aMax % 3)

# print('최대값 원소 : %f'% x[i][j])





최소값 : 0.040709624769089126
최대값 : 0.9502828643490245


In [75]:
# 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.
print('출력값 : ')
print(x)
print('행 평균의 값 :')
print(x.mean(axis = 0))
print('열 평균의 값 :')
print(x.mean(axis = 1))




출력값 : 
[[0.65358959 0.11500694 0.95028286]
 [0.4821914  0.87247454 0.21233268]
 [0.04070962 0.39719446 0.2331322 ]]
행 평균의 값 :
[0.39216354 0.46155865 0.46524925]
열 평균의 값 :
[0.5729598  0.52233287 0.22367876]
